# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5165eb990ac0808fdf9a980eb689d87beae96faa8d6e0f410f7750fda05c5d13cde6b8b4f670c8ce4176a72ff4885af839d010dbd8e21b87a2f405109d5deb65

test:
  secret_key_base: 5fb1976c95d1622ce8cbb9b3e2f41f5c4411c88cd608208bd5c6b9f308254d9f66b76e15f9cc9db18da1de57b5b5ae52a766a8190d6220e5377efb1ba0f35300

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
